[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }

env_logger =  "0.10.1"
log = { version = "0.4.20", features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"